services:
  backend:
    restart: unless-stopped
    build: .
    environment:
      - LETSENCRYPT_HOST=${HOST}
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
